### PR TITLE
Fixing git submodule to work for everyone

### PR DESCRIPTION
**Pull request by evanepio**
Fixes issue #13

### CODE REVIEW

**Comment by ncphillips** [comment]
I believe this will fix Previews in Forestry. I think this is how @jpatters said it works

**Comment by evanepio** [comment]
If I merge, will that mess up your changes, @ncphillips ? I think I should merge, but am super paranoid and untrusting of merges.

**Comment by jpatters** [comment]
@ncphillips I fixed this issue in forestry. Either url should work in previews now.
@evanepio you can merge this safely.

**Comment by ncphillips** [comment]
Thanks @jpatters 
@evanepio I don't think this will cause merge conflicts.

**Pull request merged**
